<script>
require([
    'jquery',
    'prototype',
], function(jQuery){
    function callAjax() {
        var delivery_configuration_general_environment = jQuery('#delivery_configuration_general_environment').find(":selected").val();
        var delivery_configuration_general_username = jQuery('#delivery_configuration_general_username').val();
        var delivery_configuration_general_api_key = jQuery('#delivery_configuration_general_api_key').val();
        var delivery_configuration_general_password = jQuery('#delivery_configuration_general_password').val();
        jQuery('body').trigger('processStart');
        jQuery.ajax({
          url: "<?php echo $block->getControllerUrl() ?>",
          type: "POST",
          dataType:'json',
          showLoader: true,
          data: {secret:delivery_configuration_general_api_key, username:delivery_configuration_general_username, password:delivery_configuration_general_password},
          success: function( data ) {
              jQuery('#save').addClass('submit_config');
              var data = JSON.parse(data.data);
              console.log(data);
              console.log(data.access_token);
              if(data.access_token != undefined) {
                jQuery('#delivery_configuration_general_api_key').closest('td').next().html('<span style="color:green">API configure successfully.</span>'); 
                jQuery('#delivery_configuration_general_field_hide').val(data.access_token);
                jQuery('#delivery_configuration_general_field_hide').attr('value', data.access_token);
                jQuery('#delivery_configuration_general_access_token').val(data.access_token);
                jQuery('#delivery_configuration_general_access_token').attr('value', data.access_token);
            } else {
                
                jQuery('#delivery_configuration_general_api_key').closest('td').next().html('<span style="color:red">Check credentials.</span>'); 
                jQuery('#delivery_configuration_general_access_token_hide').val('');
                jQuery('#delivery_configuration_general_access_token').val('');
            }
            jQuery('body').trigger('processStop');
              
          },
          error: function (request, status, error) {
            alert('error');
                jQuery('#delivery_configuration_general_api_key_sandbox').closest('td').next().html('<span style="color:red">Check credentials.</span>'); 
        }
        });
    }
 
    jQuery('#validate_api').click(function () {
        callAjax();
    });
    
    
    jQuery('#row_delivery_configuration_general_field_hide').css('display','none');
    jQuery('#delivery_configuration_general_access_token').val(jQuery('#delivery_configuration_general_field_hide').val());

});
</script>
<?php
    echo $block->getButtonHtml();
?>