<script>
require([
    'jquery',
    'prototype',
], function(jQuery){
    function callAjax() {
        var delivery_configuration_general_environment = jQuery('#delivery_configuration_general_environment').find(":selected").val();
        var delivery_configuration_general_username = jQuery('#delivery_configuration_general_username').val();
        var delivery_configuration_general_api_key = jQuery('#delivery_configuration_general_api_key').val();
        var delivery_configuration_general_password = jQuery('#delivery_configuration_general_password').val();
        jQuery('body').trigger('processStart');
        jQuery.ajax({
          url: "<?php echo $block->getControllerUrl('delivery/index/index') ?>",
          type: "POST",
          dataType:'json',
          showLoader: true,
          data: {secret:delivery_configuration_general_api_key, username:delivery_configuration_general_username, password:delivery_configuration_general_password},
          success: function( data ) {
              jQuery('#save').addClass('submit_config');
              var res = data;
              console.log(res);
              if(res.data !== '') {
                jQuery('#delivery_configuration_general_api_key').closest('td').next().html('<span style="color:green">API configure successfully.</span>'); 
                // jQuery('#delivery_configuration_general_access_token').val(data.access_token);
                // jQuery('#delivery_configuration_general_access_token').attr('value', data.access_token);
            } else {
                
                jQuery('#delivery_configuration_general_api_key').closest('td').next().html('<span style="color:red">Check credentials.</span>'); 
                // jQuery('#delivery_configuration_general_access_token').val('');
            }
            jQuery('body').trigger('processStop');
          },
          error: function (request, status, error) {
            alert('error');
                jQuery('#delivery_configuration_general_api_key_sandbox').closest('td').next().html('<span style="color:red">Check credentials.</span>'); 
        }
        });
    }
    
    function callAjaxForGetState() {
        var status = jQuery('#delivery_configuration_general_pharmao_delivery_active_status').val();
        
        if(status != '') {
            jQuery.ajax({
                  url: "<?php echo $block->getControllerUrl('delivery/State/index') ?>",
                  type: "POST",
                  dataType:'json',
                  showLoader: true,
                  data: {status: status},
                  success: function( data ) {
                      jQuery('#save').addClass('submit_config');
                      var data = JSON.parse(data.data);
                      jQuery('#delivery_configuration_general_pharmao_delivery_active_stat').find('option').remove();
                      jQuery('#delivery_configuration_general_pharmao_delivery_active_stat').append(data);
                      jQuery('#row_delivery_configuration_general_pharmao_delivery_active_stat').css('display','contents'); 
                      jQuery('body').trigger('processStop');
                  },
                  error: function (request, status, error) {
                    alert('error');
                }
            });    
        }
    }
 
    jQuery('#validate_api').click(function () {
        callAjax();
    });
    
    jQuery('#delivery_configuration_general_pharmao_delivery_active_status').change(function () {
        callAjaxForGetState();
    });
    
    if(jQuery('#delivery_configuration_general_pharmao_delivery_active_status').val() != '' && jQuery('#delivery_configuration_general_pharmao_delivery_active_stat').val() != null) {
        jQuery('#row_delivery_configuration_general_pharmao_delivery_active_stat').css('display','contents');    
    } else {
        jQuery('#delivery_configuration_general_pharmao_delivery_active_stat').append('<option>Select order status State</option>'); 
        jQuery('#row_delivery_configuration_general_pharmao_delivery_active_stat').css('display','none'); 
    }
    jQuery('#row_delivery_configuration_general_access_token').css('display','none');

});
</script>
<?php
    echo $block->getButtonHtml();
?>